#! /bin/sh

# Setting up sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Setting up monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# Border width stuff
bspc config border_width         1
bspc config window_gap           1

# setting other stuff?
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
bspc rule -a Emacs state=tiled
bspc rule -a dosbox state=tiled

# Autostart programs
# Background
nitrogen --restore
# Polybar setup
killall -q polybar
polybar example
# Notifications
dunst

# Fixing drawing tablet rotation, mainly an issue with my system.
# Info for this is from https://wiki.ubuntu.com/X/InputCoordinateTransformation
xinput set-prop "UGTABLET 4 inch PenTablet Pen (0)" --type=float "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1

# Fixing pycharm by changing the wm name
wmname "LG3D"
