#! /bin/sh

# Setting up sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Setting up monitors
bspc monitor -d I II III IV V VI VII VIII IX X

# Border width stuff
bspc config border_width         1
bspc config window_gap           1

# setting other stuff?
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Setting rules
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Discord desktop='^0' state=floating

# Autostart programs
nitrogen --restore
killall -q polybar
polybar example
