set number
set relativenumber
set showmatch
set mouse=v
set tabstop=2
set softtabstop=2
set shiftwidth=2
set autoindent
syntax enable
set cursorline
set background=dark
set showtabline=2
set smartindent
set nobackup
set nowritebackup
let g:coq_settings = { 'auto_start': 'shut-up' }
set ttyfast
set scrolloff=8
let g:wiki_root='~/wiki'
